export var data =[
    {
        "username": "Gina",
        //[0] == skill [1] == Behaviour
        "chess":["50","25"],
        "cards":["45","76"],
        "checkers":["95","2"],
      },
      {
        "username": "Antoinette",
        "chess":["45","30"],
        "cards":["22","33"],
        "checkers":["43","23"],
      },
      {
        "username": "Wiggins",
        "chess":["43","55"],
        "cards":["64","21"],
        "checkers":["2","45"],
      },
      {
        "username": "Sheree",
        "chess":["45","66"],
        "cards":["43","23"],
        "checkers":["12","32"],
      },
      {
        "username": "Barton",
        "chess":["43","65"],
        "cards":["22","55"],
        "checkers":["32","6"],
      },
      {
        "username": "Teresa",
        "chess":["43","30"],
        "cards":["22","23"],
        "checkers":["43","34"],
      },
      {
        "username": "Mckenzie",
        "chess":["145","30"],
        "cards":["32","33"],
        "checkers":["43","54"],
      },
      {
        "username": "Hamilton",
        "chess":["45","32"],
        "cards":["5","21"],
        "checkers":["43","23"],
      },
      {
        "username": "Conrad",
        "chess":["11","65"],
        "cards":["99","33"],
        "checkers":["32","23"],
      },
      {
        "username": "Perkins",
        "chess":["3","76"],
        "cards":["22","54"],
        "checkers":["43","3"],
      },
      {
        "username": "Celina",
        "chess":["43","30"],
        "cards":["12","33"],
        "checkers":["66","23"],
      },
      {
        "username": "Jill",
        "chess":["76","34"],
        "cards":["11","33"],
        "checkers":["32","23"],
      },
      {
        "username": "Twila",
        "chess":["66","30"],
        "cards":["22","54"],
        "checkers":["76","23"],
      },
      {
        "username": "Osborn",
        "chess":["45","77"],
        "cards":["7","66"],
        "checkers":["5","23"],
      },
      {
        "username": "Christie",
        "chess":["45","30"],
        "cards":["67","33"],
        "checkers":["43","67"],
      },
      {
        "username": "Fran",
        "chess":["45","90"],
        "cards":["88","33"],
        "checkers":["43","21"],
      },
      {
        "username": "Maricela",
        "chess":["45","30"],
        "cards":["22","11"],
        "checkers":["5","43"],
      },
      {
        "username": "Moreno",
        "chess":["66","30"],
        "cards":["22","54"],
        "checkers":["12","23"],
      },
      {
        "username": "Noel",
        "chess":["7","65"],
        "cards":["22","33"],
        "checkers":["105","23"],
      },
      {
        "username": "Armstrong",
        "chess":["2","55"],
        "cards":["2","33"],
        "checkers":["43","4"],
      },
      {
        "username": "Monroe",
        "chess":["67","30"],
        "cards":["22","77"],
        "checkers":["43","23"],
      },
      {
        "username": "Elliott",
        "chess":["45","66"],
        "cards":["26","33"],
        "checkers":["43","84"],
      },
      {
        "username": "Salas",
        "chess":["56","30"],
        "cards":["22","33"],
        "checkers":["43","78"],
      },
      {
        "username": "Judith",
        "chess":["59","30"],
        "cards":["12","33"],
        "checkers":["56","11"],
      },
      {
        "username": "Carrillo",
        "chess":["7","45"],
        "cards":["22","33"],
        "checkers":["23","23"],
      },
      {
        "username": "Lynn",
        "chess":["44","44"],
        "cards":["44","44"],
        "checkers":["44","44"],
      },
      {
        "username": "Marisa",
        "chess":["76","21"],
        "cards":["44","44"],
        "checkers":["76","32"],
      },
      {
        "username": "Anthony",
        "chess":["41","11"],
        "cards":["22","33"],
        "checkers":["17","23"],
      },
      {
        "username": "Alicia",
        "chess":["45","11"],
        "cards":["57","33"],
        "checkers":["43","67"],
      },
      {
        "username": "Ora",
        "chess":["44","30"],
        "cards":["22","86"],
        "checkers":["54","77"],
      },
      {
        "username": "Britt",
        "chess":["65","30"],
        "cards":["55","7"],
        "checkers":["43","65"],
      },
      {
        "username": "York",
        "chess":["89","30"],
        "cards":["54","33"],
        "checkers":["20","20"],
      },
      {
        "username": "Pugh",
        "chess":["96","30"],
        "cards":["22","66"],
        "checkers":["53","23"],
      },
      {
        "username": "Hunt",
        "chess":["45","43"],
        "cards":["22","33"],
        "checkers":["41","53"],
      },
      {
        "username": "Blanche",
        "chess":["44","30"],
        "cards":["78","33"],
        "checkers":["43","98"],
      },
      {
        "username": "Kay",
        "chess":["88","30"],
        "cards":["5","99"],
        "checkers":["2","23"],
      },
      {
        "username": "Sawyer",
        "chess":["45","132"],
        "cards":["22","88"],
        "checkers":["78","23"],
      },
      {
        "username": "Martinez",
        "chess":["88","66"],
        "cards":["78","33"],
        "checkers":["43","98"],
      },
      {
        "username": "Oneill",
        "chess":["45","54"],
        "cards":["42","22"],
        "checkers":["56","23"],
      },
      {
        "username": "Daniel",
        "chess":["100","30"],
        "cards":["100","96"],
        "checkers":["100","63"],
      },
      {
        "username": "Diogo",
        "chess":["100","74"],
        "cards":["100","33"],
        "checkers":["100","23"],
      },

]